name: Feedback Collection Automation

on:
  schedule:
    - cron: '0 16 * * 3' # Every Wednesday at 4 PM
  workflow_dispatch:
    inputs:
      feedback_type:
        description: 'Type of feedback to collect'
        required: true
        default: 'general'
        type: choice
        options:
          - general
          - course_specific
          - portfolio_review
          - project_feedback

jobs:
  collect-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Feedback Collection Issue
        uses: actions/github-script@v7
        with:
          script: |
            const feedbackType = core.getInput('feedback_type') || 'general';
            const date = new Date().toLocaleDateString();
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `💬 ${feedbackType} Feedback Request - ${date}`,
              body: `# Feedback Collection

## Academic Feedback Request

Requesting feedback on academic progress and portfolio development for BS IT Network & Cybersecurity program.

### Feedback Areas:
- [ ] Course understanding and progress
- [ ] Portfolio quality and presentation
- [ ] Technical skill development
- [ ] Professional growth
- [ ] Areas for improvement

### How to Provide Feedback:
1. Comment on this issue with specific observations
2. Use relevant course labels for organization
3. Be constructive and specific
4. Suggest resources or improvements

---
*Automated feedback collection for TERM-3 SY-2024-25*`,
              labels: ['feedback', 'automated', feedbackType],
              assignees: [context.repo.owner]
            });
