name: Milestone Tracking

on:
  schedule:
    - cron: '0 8 * * 1,3,5' # Monday, Wednesday, Friday at 8 AM
  workflow_dispatch:
    inputs:
      milestone_type:
        description: 'Type of milestone check'
        required: true
        default: 'weekly'
        type: choice
        options:
          - weekly
          - monthly
          - term_progress
          - course_completion

jobs:
  track-milestones:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: false

      - name: Create Milestone Issue
        uses: actions/github-script@v7
        with:
          script: |
            const courses = [
              'MO-IT103-Computer-Programming-2',
              'MO-IT143-Ethical-Hacking',
              'MO-IT147-Information-Assurance-Security-1',
              'MO-IT148-App-Dev-Emerging-Tech',
              'MO-IT151-Platform-Technologies'
            ];
            const milestoneType = core.getInput('milestone_type') || 'weekly';
            const date = new Date().toLocaleDateString();
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `📈 ${milestoneType} Milestone Check - ${date}`,
              body: `# ${milestoneType} Milestone Report

## Academic Progress Overview
Auto-generated milestone tracking for TERM-3 SY-2024-25

### Course Status
${courses.map(course => `- ${course}: Active`).join('\n')}

### Action Items
- [ ] Review progress metrics
- [ ] Update course materials
- [ ] Continue portfolio development
- [ ] Plan upcoming deadlines

---
*Automated milestone tracking*`,
              labels: ['milestone', 'automated', 'progress-tracking', milestoneType],
              assignees: [context.repo.owner]
            });
