name: Weekly Task Generator

on:
  schedule:
    - cron: '0 8 * * 1' # Every Monday at 8:00 AM
  workflow_dispatch:

jobs:
  generate-weekly-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: false  # Skip private submodule in CI

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Create weekly tasks for all courses
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          WEEK_NUM=$(date +%U)
          DATE=$(date '+%Y-%m-%d')
          COURSES=("MO-IT103-Computer-Programming-2" "MO-IT143-Ethical-Hacking" "MO-IT147-Information-Assurance-Security-1" "MO-IT148-App-Dev-Emerging-Tech" "MO-IT151-Platform-Technologies")
          for course in "${COURSES[@]}"; do
            echo "Creating weekly task issue for $course..."
            gh issue create \
              --title "📚 Week $WEEK_NUM Tasks - $course" \
              --body "## Weekly Tasks for $course
          
          ### This Week's Objectives
          - [ ] Review course materials
          - [ ] Complete assigned readings
          - [ ] Work on current assignments
          - [ ] Update portfolio items
          - [ ] Practice hands-on exercises
          
          ### Portfolio Development
          - [ ] Document learning progress
          - [ ] Create/update portfolio items
          - [ ] Gather feedback and testimonials
          
          **End of Week**: End of current week
          
          ---
          *Auto-generated weekly task for TERM-3 SY-2024-25*" \
              --label "weekly-task" \
              --label "$course" \
              --label "automated" \
              --assignee "${{ github.actor }}"
            if [ $? -eq 0 ]; then
              echo "✅ Successfully created weekly task for $course"
            else
              echo "❌ Failed to create weekly task for $course"
            fi
          done
