name: Weekly Task Generator

on:
  schedule:
    # Run every Monday at 8:00 AM
    - cron: '0 8 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  generate-weekly-tasks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Create weekly tasks for all courses
      run: |
        # Get current week number
        WEEK_NUM=$(date +%U)
        DATE=$(date '+%Y-%m-%d')
        
        # Define courses
        COURSES=("MO-IT103-Computer-Programming-2" "MO-IT143-Ethical-Hacking" "MO-IT147-Information-Assurance-Security-1" "MO-IT148-Applications-Development-Emerging-Technologies" "MO-IT151-Platform-Technologies")
        
        for course in "${COURSES[@]}"; do
          # Create GitHub issue for each course
          gh issue create \
            --title "Week $WEEK_NUM Tasks - $course" \
            --body "## Weekly Tasks for $course
        
        **Week**: $WEEK_NUM
        **Date**: $DATE
        
        ### This Week's Focus
        - [ ] Review lecture materials
        - [ ] Complete assigned readings
        - [ ] Work on current assignment
        - [ ] Update portfolio items
        - [ ] Participate in class discussions
        
        ### Deliverables Due
        - Check course schedule for specific due dates
        - Update project progress
        - Document learning achievements
        
        ### Notes
        - Track time spent on each task
        - Note any challenges or questions
        - Update course notes and documentation
        
        ---
        *Auto-generated by Weekly Task Generator*
        *TERM-3 SY-2024-25 Academic Workspace*" \
            --label "weekly-tasks,$course,automation" \
            --assignee "${{ github.actor }}"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update project board
      run: |
        echo "Weekly tasks created and assigned to project board"
        # Additional project board management can be added here
